name: Matrix-Example-CI
on:
  workflow_dispatch:  
  push:
  pull_request:

jobs:
  detect-changes:
    name: Detect changed files
    runs-on: ubuntu-latest
    outputs:
      modified_keys: ${{ steps.changed-files.outputs.modified_keys }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          matrix: true
          files_yaml: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
            database:
              - 'database/**'
            docs:
              - 'docs/**'
  matrix-job:
    name: Build and push ${{ matrix.app }}
    runs-on: ubuntu-latest
    needs: [detect-changes]
    if: needs.detect-changes.outputs.modified_keys != '[]'
    strategy:
      matrix: 
        app: ${{ fromJSON(needs.detect-changes.outputs.modified_keys) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test ${{ matrix.app }}
        run: |
          echo ${{ matrix.app }}